In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [2]:
PROJECT_ROOT = Path("..")

DATA_DIR = PROJECT_ROOT / "data"
RAW_DIR = DATA_DIR / "raw"
INTERIM_DIR = DATA_DIR / "interim"
PROCESSED_DIR = DATA_DIR / "processed"

INTERIM_DIR.mkdir(parents=True, exist_ok=True)
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

In [5]:
pollution = pd.read_csv(
    RAW_DIR / "air_pollution.csv"
)

weather = pd.read_csv(
    RAW_DIR / "weather.csv",
    skiprows=3
)

In [6]:
print("Pollution shape:", pollution.shape)
print("Weather shape:", weather.shape)

Pollution shape: (23352, 6)
Weather shape: (23352, 8)

In [7]:
pollution.head()

,time,pm10 (_g/m_),pm2_5 (_g/m_),nitrogen_dioxide (_g/m_),sulphur_dioxide (_g/m_),carbon_monoxide (_g/m_)
0,2022-09-01T00:00,53.1,37.1,29.3,5.0,765
1,2022-09-01T01:00,51.6,36.2,24.5,5.4,728
2,2022-09-01T02:00,50.6,35.5,18.8,5.8,679
3,2022-09-01T03:00,49.6,34.8,15.9,6.0,653
4,2022-09-01T04:00,47.1,33.1,13.9,6.1,629

In [8]:
weather.head()

,time,temperature_2m (°C),rain (mm),wind_direction_10m (°),wind_speed_10m (km/h),relative_humidity_2m (%),surface_pressure (hPa),dew_point_2m (°C)
0,2022-09-01T00:00,20.6,1.2,243,0.8,95,870.2,19.8
1,2022-09-01T01:00,20.7,8.4,194,1.5,95,870.9,19.8
2,2022-09-01T02:00,20.9,9.5,225,1.5,94,871.7,19.9
3,2022-09-01T03:00,21.1,7.2,207,0.8,94,872.4,20.2
4,2022-09-01T04:00,21.4,2.6,45,1.0,93,873.0,20.3

In [10]:
pollution.tail()

,time,pm10 (_g/m_),pm2_5 (_g/m_),nitrogen_dioxide (_g/m_),sulphur_dioxide (_g/m_),carbon_monoxide (_g/m_)
23347,2025-04-30T19:00,45.2,35.7,17.9,6.6,1143
23348,2025-04-30T20:00,49.1,40.4,22.9,7.5,1393
23349,2025-04-30T21:00,52.5,44.6,25.2,7.7,1482
23350,2025-04-30T22:00,51.7,44.6,26.1,7.6,1478
23351,2025-04-30T23:00,47.5,41.3,25.9,7.3,1407

In [11]:
weather.tail()

,time,temperature_2m (°C),rain (mm),wind_direction_10m (°),wind_speed_10m (km/h),relative_humidity_2m (%),surface_pressure (hPa),dew_point_2m (°C)
23347,2025-04-30T19:00,15.2,0.0,162,6.4,88,872.0,13.2
23348,2025-04-30T20:00,15.1,0.0,164,6.7,88,871.7,13.0
23349,2025-04-30T21:00,14.7,0.0,163,5.1,90,871.5,13.0
23350,2025-04-30T22:00,14.8,0.0,160,5.8,89,871.9,13.0
23351,2025-04-30T23:00,14.8,0.0,180,1.3,89,872.6,13.0

In [12]:
print("Pollution columns:")
print(pollution.columns.tolist())

print("\nWeather columns:")
print(weather.columns.tolist())

Pollution columns:
['time', 'pm10 (_g/m_)', 'pm2_5 (_g/m_)', 'nitrogen_dioxide (_g/m_)', 'sulphur_dioxide (_g/m_)', 'carbon_monoxide (_g/m_)']

Weather columns:
['time', 'temperature_2m (°C)', 'rain (mm)', 'wind_direction_10m (°)', 'wind_speed_10m (km/h)', 'relative_humidity_2m (%)', 'surface_pressure (hPa)', 'dew_point_2m (°C)']

In [13]:
pollution.info()

<class 'pandas.DataFrame'>
RangeIndex: 23352 entries, 0 to 23351
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   time                      23352 non-null  str
 1   pm10 (_g/m_)              23352 non-null  float64
 2   pm2_5 (_g/m_)             23352 non-null  float64
 3   nitrogen_dioxide (_g/m_)  23352 non-null  float64
 4   sulphur_dioxide (_g/m_)   23352 non-null  float64
 5   carbon_monoxide (_g/m_)   23352 non-null  int64
dtypes: float64(4), int64(1), str(1)
memory usage: 1.4 MB

In [14]:
weather.info()

<class 'pandas.DataFrame'>
RangeIndex: 23352 entries, 0 to 23351
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   time                      23352 non-null  str
 1   temperature_2m (°C)       23352 non-null  float64
 2   rain (mm)                 23352 non-null  float64
 3   wind_direction_10m (°)    23352 non-null  int64
 4   wind_speed_10m (km/h)     23352 non-null  float64
 5   relative_humidity_2m (%)  23352 non-null  int64
 6   surface_pressure (hPa)    23352 non-null  float64
 7   dew_point_2m (°C)         23352 non-null  float64
dtypes: float64(5), int64(2), str(1)
memory usage: 1.8 MB

In [15]:
pollution.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
time,23352,23352,2022-09-01T00:00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pm10 (_g/m_),23352.0,NaN,NaN,NaN,48.610517,28.368394,0.3,27.4,42.3,64.5,221.2
pm2_5 (_g/m_),23352.0,NaN,NaN,NaN,35.045422,23.25226,0.2,18.8,29.0,44.6,170.4
nitrogen_dioxide (_g/m_),23352.0,NaN,NaN,NaN,14.271446,13.574662,0.0,3.7,10.6,20.7,107.3
sulphur_dioxide (_g/m_),23352.0,NaN,NaN,NaN,6.76775,4.767855,0.0,3.7,5.6,8.3,37.5
carbon_monoxide (_g/m_),23352.0,NaN,NaN,NaN,669.837359,469.375936,59.0,333.0,523.0,839.0,3204.0

In [16]:
weather.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
time,23352,23352,2022-09-01T00:00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
temperature_2m (°C),23352.0,NaN,NaN,NaN,17.811986,5.825566,1.3,13.3,18.7,22.0,32.6
rain (mm),23352.0,NaN,NaN,NaN,0.224289,1.041249,0.0,0.0,0.0,0.0,23.1
wind_direction_10m (°),23352.0,NaN,NaN,NaN,203.802073,87.014629,2.0,165.0,175.0,297.0,360.0
wind_speed_10m (km/h),23352.0,NaN,NaN,NaN,4.106539,2.313208,0.0,2.5,3.7,5.3,18.8
relative_humidity_2m (%),23352.0,NaN,NaN,NaN,73.341384,20.505056,7.0,60.0,77.0,91.0,100.0
surface_pressure (hPa),23352.0,NaN,NaN,NaN,871.241076,3.278988,860.4,869.0,871.2,873.5,881.6
dew_point_2m (°C),23352.0,NaN,NaN,NaN,12.223544,6.473807,-9.5,7.0,11.4,19.0,23.4

In [18]:
print(pollution.columns.tolist())
print(weather.columns.tolist())

['time', 'pm10 (_g/m_)', 'pm2_5 (_g/m_)', 'nitrogen_dioxide (_g/m_)', 'sulphur_dioxide (_g/m_)', 'carbon_monoxide (_g/m_)']
['time', 'temperature_2m (°C)', 'rain (mm)', 'wind_direction_10m (°)', 'wind_speed_10m (km/h)', 'relative_humidity_2m (%)', 'surface_pressure (hPa)', 'dew_point_2m (°C)']

In [19]:
pollution_raw = pollution.copy()
weather_raw = weather.copy()

In [20]:
print("Pollution dataset shape:", pollution.shape)
print("Weather dataset shape:", weather.shape)

print("\nPollution columns:")
print(pollution.columns.tolist())

print("\nWeather columns:")
print(weather.columns.tolist())

Pollution dataset shape: (23352, 6)
Weather dataset shape: (23352, 8)

Pollution columns:
['time', 'pm10 (_g/m_)', 'pm2_5 (_g/m_)', 'nitrogen_dioxide (_g/m_)', 'sulphur_dioxide (_g/m_)', 'carbon_monoxide (_g/m_)']

Weather columns:
['time', 'temperature_2m (°C)', 'rain (mm)', 'wind_direction_10m (°)', 'wind_speed_10m (km/h)', 'relative_humidity_2m (%)', 'surface_pressure (hPa)', 'dew_point_2m (°C)']

In [21]:
display(pollution.head())
display(weather.head())

,time,pm10 (_g/m_),pm2_5 (_g/m_),nitrogen_dioxide (_g/m_),sulphur_dioxide (_g/m_),carbon_monoxide (_g/m_)
0,2022-09-01T00:00,53.1,37.1,29.3,5.0,765
1,2022-09-01T01:00,51.6,36.2,24.5,5.4,728
2,2022-09-01T02:00,50.6,35.5,18.8,5.8,679
3,2022-09-01T03:00,49.6,34.8,15.9,6.0,653
4,2022-09-01T04:00,47.1,33.1,13.9,6.1,629

,time,temperature_2m (°C),rain (mm),wind_direction_10m (°),wind_speed_10m (km/h),relative_humidity_2m (%),surface_pressure (hPa),dew_point_2m (°C)
0,2022-09-01T00:00,20.6,1.2,243,0.8,95,870.2,19.8
1,2022-09-01T01:00,20.7,8.4,194,1.5,95,870.9,19.8
2,2022-09-01T02:00,20.9,9.5,225,1.5,94,871.7,19.9
3,2022-09-01T03:00,21.1,7.2,207,0.8,94,872.4,20.2
4,2022-09-01T04:00,21.4,2.6,45,1.0,93,873.0,20.3

In [22]:
pollution.info()

<class 'pandas.DataFrame'>
RangeIndex: 23352 entries, 0 to 23351
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   time                      23352 non-null  str
 1   pm10 (_g/m_)              23352 non-null  float64
 2   pm2_5 (_g/m_)             23352 non-null  float64
 3   nitrogen_dioxide (_g/m_)  23352 non-null  float64
 4   sulphur_dioxide (_g/m_)   23352 non-null  float64
 5   carbon_monoxide (_g/m_)   23352 non-null  int64
dtypes: float64(4), int64(1), str(1)
memory usage: 1.4 MB

In [23]:
weather.info()

<class 'pandas.DataFrame'>
RangeIndex: 23352 entries, 0 to 23351
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   time                      23352 non-null  str
 1   temperature_2m (°C)       23352 non-null  float64
 2   rain (mm)                 23352 non-null  float64
 3   wind_direction_10m (°)    23352 non-null  int64
 4   wind_speed_10m (km/h)     23352 non-null  float64
 5   relative_humidity_2m (%)  23352 non-null  int64
 6   surface_pressure (hPa)    23352 non-null  float64
 7   dew_point_2m (°C)         23352 non-null  float64
dtypes: float64(5), int64(2), str(1)
memory usage: 1.8 MB

In [24]:
#rename columns
pollution = pollution.rename(columns={
    'pm10 (_g/m_)': 'pm10',
    'pm2_5 (_g/m_)': 'pm25',
    'nitrogen_dioxide (_g/m_)': 'no2',
    'sulphur_dioxide (_g/m_)': 'so2',
    'carbon_monoxide (_g/m_)': 'co'
})

In [25]:
weather = weather.rename(columns={
    'temperature_2m (°C)': 'temperature',
    'rain (mm)': 'rain',
    'wind_direction_10m (°)': 'wind_direction',
    'wind_speed_10m (km/h)': 'wind_speed',
    'relative_humidity_2m (%)': 'humidity',
    'surface_pressure (hPa)': 'pressure',
    'dew_point_2m (°C)': 'dew_point'
})

In [26]:
print("Pollution:")
print(pollution.columns.tolist())

print("\nWeather:")
print(weather.columns.tolist())

Pollution:
['time', 'pm10', 'pm25', 'no2', 'so2', 'co']

Weather:
['time', 'temperature', 'rain', 'wind_direction', 'wind_speed', 'humidity', 'pressure', 'dew_point']

In [27]:
print(pollution['time'].head())
print(weather['time'].head())

0    2022-09-01T00:00
1    2022-09-01T01:00
2    2022-09-01T02:00
3    2022-09-01T03:00
4    2022-09-01T04:00
Name: time, dtype: str
0    2022-09-01T00:00
1    2022-09-01T01:00
2    2022-09-01T02:00
3    2022-09-01T03:00
4    2022-09-01T04:00
Name: time, dtype: str

In [28]:
#date type
pollution['time'] = pd.to_datetime(
    pollution['time'],
    errors='coerce'
)

weather['time'] = pd.to_datetime(
    weather['time'],
    errors='coerce'
)

In [29]:
print(
    "Invalid pollution timestamps:",
    pollution['time'].isna().sum()
)

print(
    "Invalid weather timestamps:",
    weather['time'].isna().sum()
)

Invalid pollution timestamps: 0
Invalid weather timestamps: 0

In [30]:
print(pollution['time'].dtype)
print(weather['time'].dtype)

datetime64[us]
datetime64[us]

In [31]:
pollution = (
    pollution
    .sort_values('time')
    .reset_index(drop=True)
)

weather = (
    weather
    .sort_values('time')
    .reset_index(drop=True)
)

In [32]:
display(pollution.head())
display(pollution.tail())

                 time  pm10  pm25   no2  so2   co
0 2022-09-01 00:00:00  53.1  37.1  29.3  5.0  765
1 2022-09-01 01:00:00  51.6  36.2  24.5  5.4  728
2 2022-09-01 02:00:00  50.6  35.5  18.8  5.8  679
3 2022-09-01 03:00:00  49.6  34.8  15.9  6.0  653
4 2022-09-01 04:00:00  47.1  33.1  13.9  6.1  629

                     time  pm10  pm25   no2  so2    co
23347 2025-04-30 19:00:00  45.2  35.7  17.9  6.6  1143
23348 2025-04-30 20:00:00  49.1  40.4  22.9  7.5  1393
23349 2025-04-30 21:00:00  52.5  44.6  25.2  7.7  1482
23350 2025-04-30 22:00:00  51.7  44.6  26.1  7.6  1478
23351 2025-04-30 23:00:00  47.5  41.3  25.9  7.3  1407

In [33]:
display(weather.head())
display(weather.tail())

,time,temperature,rain,wind_direction,wind_speed,humidity,pressure,dew_point
0,2022-09-01 00:00:00,20.6,1.2,243,0.8,95,870.2,19.8
1,2022-09-01 01:00:00,20.7,8.4,194,1.5,95,870.9,19.8
2,2022-09-01 02:00:00,20.9,9.5,225,1.5,94,871.7,19.9
3,2022-09-01 03:00:00,21.1,7.2,207,0.8,94,872.4,20.2
4,2022-09-01 04:00:00,21.4,2.6,45,1.0,93,873.0,20.3

,time,temperature,rain,wind_direction,wind_speed,humidity,pressure,dew_point
23347,2025-04-30 19:00:00,15.2,0.0,162,6.4,88,872.0,13.2
23348,2025-04-30 20:00:00,15.1,0.0,164,6.7,88,871.7,13.0
23349,2025-04-30 21:00:00,14.7,0.0,163,5.1,90,871.5,13.0
23350,2025-04-30 22:00:00,14.8,0.0,160,5.8,89,871.9,13.0
23351,2025-04-30 23:00:00,14.8,0.0,180,1.3,89,872.6,13.0

In [34]:
print("POLLUTION")
print("Start:", pollution['time'].min())
print("End:  ", pollution['time'].max())
print("Rows: ", len(pollution))

print("\nWEATHER")
print("Start:", weather['time'].min())
print("End:  ", weather['time'].max())
print("Rows: ", len(weather))

POLLUTION
Start: 2022-09-01 00:00:00
End:   2025-04-30 23:00:00
Rows:  23352

WEATHER
Start: 2022-09-01 00:00:00
End:   2025-04-30 23:00:00
Rows:  23352

In [35]:
print(
    "Duplicate pollution rows:",
    pollution.duplicated().sum()
)

print(
    "Duplicate weather rows:",
    weather.duplicated().sum()
)

Duplicate pollution rows: 0
Duplicate weather rows: 0

In [36]:
print(
    "Duplicate pollution timestamps:",
    pollution.duplicated(
        subset='time'
    ).sum()
)

print(
    "Duplicate weather timestamps:",
    weather.duplicated(
        subset='time'
    ).sum()
)

Duplicate pollution timestamps: 0
Duplicate weather timestamps: 0

In [37]:
#missing value analysis
def missing_summary(df):
    summary = pd.DataFrame({
        'missing_count': df.isna().sum(),
        'missing_percent': df.isna().mean() * 100
    })

    return summary.sort_values(
        by='missing_percent',
        ascending=False
    )

In [38]:
missing_summary(pollution)

      missing_count  missing_percent
time              0              0.0
pm10              0              0.0
pm25              0              0.0
no2               0              0.0
so2               0              0.0
co                0              0.0

In [39]:
missing_summary(weather)

                missing_count  missing_percent
time                        0              0.0
temperature                 0              0.0
rain                        0              0.0
wind_direction              0              0.0
wind_speed                  0              0.0
humidity                    0              0.0
pressure                    0              0.0
dew_point                   0              0.0

In [40]:
#numeric data type
pollution.dtypes

time    datetime64[us]
pm10           float64
pm25           float64
no2            float64
so2            float64
co               int64
dtype: object

In [41]:
weather.dtypes

time              datetime64[us]
temperature              float64
rain                     float64
wind_direction             int64
wind_speed               float64
humidity                   int64
pressure                 float64
dew_point                float64
dtype: object

In [42]:
pollution.select_dtypes(
    exclude=['number', 'datetime']
).columns.tolist()

[]

In [43]:
weather.select_dtypes(
    exclude=['number', 'datetime']
).columns.tolist()

[]

In [44]:
#descriptive statistics
pollution.describe().T

,count,mean,min,25%,50%,75%,max,std
time,23352,2023-12-31 11:29:59.999999,2022-09-01 00:00:00,2023-05-02 05:45:00,2023-12-31 11:30:00,2024-08-30 17:15:00,2025-04-30 23:00:00,NaN
pm10,23352.0,48.610517,0.3,27.4,42.3,64.5,221.2,28.368394
pm25,23352.0,35.045422,0.2,18.8,29.0,44.6,170.4,23.25226
no2,23352.0,14.271446,0.0,3.7,10.6,20.7,107.3,13.574662
so2,23352.0,6.76775,0.0,3.7,5.6,8.3,37.5,4.767855
co,23352.0,669.837359,59.0,333.0,523.0,839.0,3204.0,469.375936

In [45]:
weather.describe().T

,count,mean,min,25%,50%,75%,max,std
time,23352,2023-12-31 11:29:59.999999,2022-09-01 00:00:00,2023-05-02 05:45:00,2023-12-31 11:30:00,2024-08-30 17:15:00,2025-04-30 23:00:00,NaN
temperature,23352.0,17.811986,1.3,13.3,18.7,22.0,32.6,5.825566
rain,23352.0,0.224289,0.0,0.0,0.0,0.0,23.1,1.041249
wind_direction,23352.0,203.802073,2.0,165.0,175.0,297.0,360.0,87.014629
wind_speed,23352.0,4.106539,0.0,2.5,3.7,5.3,18.8,2.313208
humidity,23352.0,73.341384,7.0,60.0,77.0,91.0,100.0,20.505056
pressure,23352.0,871.241076,860.4,869.0,871.2,873.5,881.6,3.278988
dew_point,23352.0,12.223544,-9.5,7.0,11.4,19.0,23.4,6.473807

In [46]:
#physical-validity check
pollutant_columns = [
    'pm10',
    'pm25',
    'no2',
    'so2',
    'co'
]

for column in pollutant_columns:
    negative_count = (pollution[column] < 0).sum()

    print(
        f"{column}: {negative_count} negative values"
    )

pm10: 0 negative values
pm25: 0 negative values
no2: 0 negative values
so2: 0 negative values
co: 0 negative values

In [47]:
print(
    "Humidity below 0:",
    (weather['humidity'] < 0).sum()
)

print(
    "Humidity above 100:",
    (weather['humidity'] > 100).sum()
)

print(
    "Negative rain:",
    (weather['rain'] < 0).sum()
)

print(
    "Negative wind speed:",
    (weather['wind_speed'] < 0).sum()
)

print(
    "Wind direction below 0:",
    (weather['wind_direction'] < 0).sum()
)

print(
    "Wind direction above 360:",
    (weather['wind_direction'] > 360).sum()
)

Humidity below 0: 0
Humidity above 100: 0
Negative rain: 0
Negative wind speed: 0
Wind direction below 0: 0
Wind direction above 360: 0

In [48]:
#timestamp spacing
pollution_time_differences = (
    pollution['time']
    .diff()
    .value_counts()
    .sort_index()
)

pollution_time_differences

time
0 days 01:00:00    23351
Name: count, dtype: int64

In [49]:
weather_time_differences = (
    weather['time']
    .diff()
    .value_counts()
    .sort_index()
)

weather_time_differences

time
0 days 01:00:00    23351
Name: count, dtype: int64

In [50]:
#missing timestamps
expected_pollution_index = pd.date_range(
    start=pollution['time'].min(),
    end=pollution['time'].max(),
    freq='h'
)

missing_pollution_times = (
    expected_pollution_index
    .difference(
        pd.DatetimeIndex(pollution['time'])
    )
)

print(
    "Expected pollution observations:",
    len(expected_pollution_index)
)

print(
    "Actual pollution observations:",
    len(pollution)
)

print(
    "Missing pollution timestamps:",
    len(missing_pollution_times)
)

Expected pollution observations: 23352
Actual pollution observations: 23352
Missing pollution timestamps: 0

In [51]:
expected_weather_index = pd.date_range(
    start=weather['time'].min(),
    end=weather['time'].max(),
    freq='h'
)

missing_weather_times = (
    expected_weather_index
    .difference(
        pd.DatetimeIndex(weather['time'])
    )
)

print(
    "Expected weather observations:",
    len(expected_weather_index)
)

print(
    "Actual weather observations:",
    len(weather)
)

print(
    "Missing weather timestamps:",
    len(missing_weather_times)
)

Expected weather observations: 23352
Actual weather observations: 23352
Missing weather timestamps: 0

In [52]:
#temporal completeness
pollution_completeness = (
    len(pollution)
    / len(expected_pollution_index)
    * 100
)

weather_completeness = (
    len(weather)
    / len(expected_weather_index)
    * 100
)

print(
    f"Pollution temporal completeness: "
    f"{pollution_completeness:.2f}%"
)

print(
    f"Weather temporal completeness: "
    f"{weather_completeness:.2f}%"
)

Pollution temporal completeness: 100.00%
Weather temporal completeness: 100.00%

In [53]:
#time overlap before merging
overlap_start = max(
    pollution['time'].min(),
    weather['time'].min()
)

overlap_end = min(
    pollution['time'].max(),
    weather['time'].max()
)

print("Common start:", overlap_start)
print("Common end:", overlap_end)

Common start: 2022-09-01 00:00:00
Common end: 2025-04-30 23:00:00

In [54]:
pollution_only_times = (
    set(pollution['time'])
    - set(weather['time'])
)

weather_only_times = (
    set(weather['time'])
    - set(pollution['time'])
)

print(
    "Pollution timestamps without weather:",
    len(pollution_only_times)
)

print(
    "Weather timestamps without pollution:",
    len(weather_only_times)
)

Pollution timestamps without weather: 0
Weather timestamps without pollution: 0

In [55]:
#merging dataset
df = pd.merge(
    pollution,
    weather,
    on='time',
    how='inner',
    validate='one_to_one'
)

In [56]:
print("Pollution rows:", len(pollution))
print("Weather rows:", len(weather))
print("Merged rows:", len(df))

Pollution rows: 23352
Weather rows: 23352
Merged rows: 23352

In [57]:
df.head()

,time,pm10,pm25,no2,so2,co,temperature,rain,wind_direction,wind_speed,humidity,pressure,dew_point
0,2022-09-01 00:00:00,53.1,37.1,29.3,5.0,765,20.6,1.2,243,0.8,95,870.2,19.8
1,2022-09-01 01:00:00,51.6,36.2,24.5,5.4,728,20.7,8.4,194,1.5,95,870.9,19.8
2,2022-09-01 02:00:00,50.6,35.5,18.8,5.8,679,20.9,9.5,225,1.5,94,871.7,19.9
3,2022-09-01 03:00:00,49.6,34.8,15.9,6.0,653,21.1,7.2,207,0.8,94,872.4,20.2
4,2022-09-01 04:00:00,47.1,33.1,13.9,6.1,629,21.4,2.6,45,1.0,93,873.0,20.3

In [58]:
df.tail()

,time,pm10,pm25,no2,so2,co,temperature,rain,wind_direction,wind_speed,humidity,pressure,dew_point
23347,2025-04-30 19:00:00,45.2,35.7,17.9,6.6,1143,15.2,0.0,162,6.4,88,872.0,13.2
23348,2025-04-30 20:00:00,49.1,40.4,22.9,7.5,1393,15.1,0.0,164,6.7,88,871.7,13.0
23349,2025-04-30 21:00:00,52.5,44.6,25.2,7.7,1482,14.7,0.0,163,5.1,90,871.5,13.0
23350,2025-04-30 22:00:00,51.7,44.6,26.1,7.6,1478,14.8,0.0,160,5.8,89,871.9,13.0
23351,2025-04-30 23:00:00,47.5,41.3,25.9,7.3,1407,14.8,0.0,180,1.3,89,872.6,13.0

In [59]:
df.columns.tolist()

['time',
 'pm10',
 'pm25',
 'no2',
 'so2',
 'co',
 'temperature',
 'rain',
 'wind_direction',
 'wind_speed',
 'humidity',
 'pressure',
 'dew_point']

In [60]:
#time as the dataframe index
df = (
    df
    .sort_values('time')
    .set_index('time')
)

In [61]:
df.head()

,pm10,pm25,no2,so2,co,temperature,rain,wind_direction,wind_speed,humidity,pressure,dew_point
time,,,,,,,,,,,,
2022-09-01 00:00:00,53.1,37.1,29.3,5.0,765,20.6,1.2,243,0.8,95,870.2,19.8
2022-09-01 01:00:00,51.6,36.2,24.5,5.4,728,20.7,8.4,194,1.5,95,870.9,19.8
2022-09-01 02:00:00,50.6,35.5,18.8,5.8,679,20.9,9.5,225,1.5,94,871.7,19.9
2022-09-01 03:00:00,49.6,34.8,15.9,6.0,653,21.1,7.2,207,0.8,94,872.4,20.2
2022-09-01 04:00:00,47.1,33.1,13.9,6.1,629,21.4,2.6,45,1.0,93,873.0,20.3

In [62]:
print(type(df.index))

<class 'pandas.DatetimeIndex'>

In [63]:
#index properties
print(
    "Index is monotonic:",
    df.index.is_monotonic_increasing
)

print(
    "Index is unique:",
    df.index.is_unique
)

Index is monotonic: True
Index is unique: True

In [64]:
#time-series frequency
frequency = pd.infer_freq(df.index)

print(
    "Inferred frequency:",
    frequency
)

Inferred frequency: h

In [65]:
missing_summary(df)

                missing_count  missing_percent
pm10                        0              0.0
pm25                        0              0.0
no2                         0              0.0
so2                         0              0.0
co                          0              0.0
temperature                 0              0.0
rain                        0              0.0
wind_direction              0              0.0
wind_speed                  0              0.0
humidity                    0              0.0
pressure                    0              0.0
dew_point                   0              0.0

In [66]:
#duplicate-index check
print(
    "Duplicate timestamps in merged data:",
    df.index.duplicated().sum()
)

Duplicate timestamps in merged data: 0

In [67]:
#descriptive summary
numeric_columns = df.select_dtypes(
    include=np.number
).columns

In [68]:
data_summary = pd.DataFrame({
    'count': df[numeric_columns].count(),
    'mean': df[numeric_columns].mean(),
    'median': df[numeric_columns].median(),
    'std': df[numeric_columns].std(),
    'min': df[numeric_columns].min(),
    'q25': df[numeric_columns].quantile(0.25),
    'q75': df[numeric_columns].quantile(0.75),
    'max': df[numeric_columns].max(),
    'missing': df[numeric_columns].isna().sum()
})

data_summary

,count,mean,median,std,min,q25,q75,max,missing
pm10,23352,48.610517,42.3,28.368394,0.3,27.4,64.5,221.2,0
pm25,23352,35.045422,29.0,23.252260,0.2,18.8,44.6,170.4,0
no2,23352,14.271446,10.6,13.574662,0.0,3.7,20.7,107.3,0
so2,23352,6.767750,5.6,4.767855,0.0,3.7,8.3,37.5,0
co,23352,669.837359,523.0,469.375936,59.0,333.0,839.0,3204.0,0
temperature,23352,17.811986,18.7,5.825566,1.3,13.3,22.0,32.6,0
rain,23352,0.224289,0.0,1.041249,0.0,0.0,0.0,23.1,0
wind_direction,23352,203.802073,175.0,87.014629,2.0,165.0,297.0,360.0,0
wind_speed,23352,4.106539,3.7,2.313208,0.0,2.5,5.3,18.8,0
humidity,23352,73.341384,77.0,20.505056,7.0,60.0,91.0,100.0,0
pressure,23352,871.241076,871.2,3.278988,860.4,869.0,873.5,881.6,0
dew_point,23352,12.223544,11.4,6.473807,-9.5,7.0,19.0,23.4,0

In [69]:
phase1_report = {
    'pollution_rows': len(pollution),
    'weather_rows': len(weather),
    'merged_rows': len(df),

    'start_date': df.index.min(),
    'end_date': df.index.max(),

    'inferred_frequency': pd.infer_freq(df.index),

    'duplicate_timestamps':
        int(df.index.duplicated().sum()),

    'total_missing_values':
        int(df.isna().sum().sum()),

    'pollution_only_timestamps':
        len(pollution_only_times),

    'weather_only_timestamps':
        len(weather_only_times),

    'number_of_variables':
        df.shape[1]
}

phase1_report

{'pollution_rows': 23352,
 'weather_rows': 23352,
 'merged_rows': 23352,
 'start_date': Timestamp('2022-09-01 00:00:00'),
 'end_date': Timestamp('2025-04-30 23:00:00'),
 'inferred_frequency': 'h',
 'duplicate_timestamps': 0,
 'total_missing_values': 0,
 'pollution_only_timestamps': 0,
 'weather_only_timestamps': 0,
 'number_of_variables': 12}

In [70]:
from pathlib import Path

INTERIM_DIR = Path("../data/interim")

INTERIM_DIR.mkdir(
    parents=True,
    exist_ok=True
)

In [71]:
df.to_csv(
    INTERIM_DIR / "merged_air_quality.csv"
)

In [72]:
print(
    "Saved:",
    INTERIM_DIR / "merged_air_quality.csv"
)

Saved: ../data/interim/merged_air_quality.csv

In [73]:
#test
test_load = pd.read_csv(
    INTERIM_DIR / "merged_air_quality.csv",
    parse_dates=['time'],
    index_col='time'
)

test_load.head()

,pm10,pm25,no2,so2,co,temperature,rain,wind_direction,wind_speed,humidity,pressure,dew_point
time,,,,,,,,,,,,
2022-09-01 00:00:00,53.1,37.1,29.3,5.0,765,20.6,1.2,243,0.8,95,870.2,19.8
2022-09-01 01:00:00,51.6,36.2,24.5,5.4,728,20.7,8.4,194,1.5,95,870.9,19.8
2022-09-01 02:00:00,50.6,35.5,18.8,5.8,679,20.9,9.5,225,1.5,94,871.7,19.9
2022-09-01 03:00:00,49.6,34.8,15.9,6.0,653,21.1,7.2,207,0.8,94,872.4,20.2
2022-09-01 04:00:00,47.1,33.1,13.9,6.1,629,21.4,2.6,45,1.0,93,873.0,20.3

In [74]:
print(test_load.shape)
print(type(test_load.index))
print(test_load.index.min())
print(test_load.index.max())

(23352, 12)
<class 'pandas.DatetimeIndex'>
2022-09-01 00:00:00
2025-04-30 23:00:00

In [75]:
assert test_load.shape == df.shape

In [76]:
print("=" * 60)
print("PHASE 1 — DATA INTEGRATION SUMMARY")
print("=" * 60)

print(f"\nObservations: {len(df):,}")
print(f"Variables: {df.shape[1]}")

print(
    f"Period: {df.index.min()} "
    f"to {df.index.max()}"
)

print(
    f"Frequency: {pd.infer_freq(df.index)}"
)

print(
    f"Duplicate timestamps: "
    f"{df.index.duplicated().sum()}"
)

print(
    f"Missing values: "
    f"{df.isna().sum().sum()}"
)

print(
    f"Pollution timestamps without weather: "
    f"{len(pollution_only_times)}"
)

print(
    f"Weather timestamps without pollution: "
    f"{len(weather_only_times)}"
)

print("\nVariables:")
for column in df.columns:
    print(f"  - {column}")

print("\n" + "=" * 60)

============================================================
PHASE 1 — DATA INTEGRATION SUMMARY
============================================================

Observations: 23,352
Variables: 12
Period: 2022-09-01 00:00:00 to 2025-04-30 23:00:00
Frequency: h
Duplicate timestamps: 0
Missing values: 0
Pollution timestamps without weather: 0
Weather timestamps without pollution: 0

Variables:
  - pm10
  - pm25
  - no2
  - so2
  - co
  - temperature
  - rain
  - wind_direction
  - wind_speed
  - humidity
  - pressure
  - dew_point

============================================================

## Summary: Data Acquisition and Integration

The air-pollution and meteorological datasets were imported separately,
their timestamps were standardized, and both datasets were evaluated for
missing records, duplicate timestamps, invalid values, and temporal
continuity.

The datasets were then aligned using their hourly timestamps through a
one-to-one inner join. The resulting integrated dataset contains pollution
measurements (PM2.5, PM10, NO₂, SO₂, and CO) together with meteorological
variables including temperature, rainfall, wind direction, wind speed,
relative humidity, surface pressure, and dew point.

The merged dataset was sorted chronologically and stored using a
DatetimeIndex to support subsequent time-series analysis.

No outlier removal or statistical transformations were performed during
this stage. Data-quality issues and potential extreme observations will be
examined separately during Phase 2.

In [77]:
print(df.shape)
print(df.index.min(), df.index.max())
print(pd.infer_freq(df.index))
print(df.isna().sum())
print(phase1_report)

(23352, 12)
2022-09-01 00:00:00 2025-04-30 23:00:00
h
pm10              0
pm25              0
no2               0
so2               0
co                0
temperature       0
rain              0
wind_direction    0
wind_speed        0
humidity          0
pressure          0
dew_point         0
dtype: int64
{'pollution_rows': 23352, 'weather_rows': 23352, 'merged_rows': 23352, 'start_date': Timestamp('2022-09-01 00:00:00'), 'end_date': Timestamp('2025-04-30 23:00:00'), 'inferred_frequency': 'h', 'duplicate_timestamps': 0, 'total_missing_values': 0, 'pollution_only_timestamps': 0, 'weather_only_timestamps': 0, 'number_of_variables': 12}